#!/usr/bin/expect
set user [lindex $argv 1]
set ip [lindex $argv 0]
set password [lindex $argv 2]
set password_en [lindex $argv 3]
set interface_name [lindex $argv 4]
set interface_ip [lindex $argv 5]
set interface_mask [lindex $argv 6]
spawn ssh $user@$ip
sleep 3
send "$password\n"
sleep 1
send "en\n"
sleep 1
send "$password_en\n"
sleep 1
send "conf t\n"
sleep 1
send "interface $interface_name\n"
sleep 1
send "ip address $interface_ip $interface_mask\n"
sleep 1
send "no sh\n"
sleep 1
send "exit\n"
sleep 1
send "exit\n"
sleep 5
send "wr\n"
sleep 1
send "exit\n"
interact
